<a href="https://colab.research.google.com/github/tanusattri/Data-Cleaning/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#handling missing data
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvak', 'artichoke', np.nan, 'avocado'])
string_data

0      aardvak
1    artichoke
2          NaN
3      avocado
dtype: object

In [ ]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                   [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
print(cleaned)

     0    1    2
0  1.0  6.5  3.0

In [ ]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data[4] = NA
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

          0         1         2
0 -1.339823       NaN       NaN
1 -0.182884       NaN       NaN
2  0.052101       NaN  0.326313
3 -0.098808       NaN  0.722825
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
df.dropna()

          0         1         2
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
df.dropna(thresh=2)

          0         1         2
2  0.052101       NaN  0.326313
3 -0.098808       NaN  0.722825
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
#Filling In Missing Data
df.fillna(0)

          0         1         2
0 -1.339823  0.000000  0.000000
1 -0.182884  0.000000  0.000000
2  0.052101  0.000000  0.326313
3 -0.098808  0.000000  0.722825
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
df.fillna({1:0.5, 2: 0})

          0         1         2
0 -1.339823  0.500000  0.000000
1 -0.182884  0.500000  0.000000
2  0.052101  0.500000  0.326313
3 -0.098808  0.500000  0.722825
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
_ = df.fillna(0, inplace=True)
df

          0         1         2
0 -1.339823  0.000000  0.000000
1 -0.182884  0.000000  0.000000
2  0.052101  0.000000  0.326313
3 -0.098808  0.000000  0.722825
4 -1.218445  0.343116 -0.743747
5 -1.860601 -1.093862  1.217806
6 -0.908017 -0.025580  0.157189

In [ ]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

          0         1         2
0 -0.846177 -0.453802 -0.377466
1 -1.126541  1.639320  0.656015
2 -0.666795       NaN  1.061254
3  0.747985       NaN -1.037145
4  0.136393       NaN       NaN
5 -0.109069       NaN       NaN

In [ ]:
df.fillna(method='ffill')

/tmp/ipython-input-1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

          0         1         2
0 -0.846177 -0.453802 -0.377466
1 -1.126541  1.639320  0.656015
2 -0.666795  1.639320  1.061254
3  0.747985  1.639320 -1.037145
4  0.136393  1.639320 -1.037145
5 -0.109069  1.639320 -1.037145

In [ ]:
df.fillna(method='ffill', limit=2)

/tmp/ipython-input-2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

          0         1         2
0 -0.846177 -0.453802 -0.377466
1 -1.126541  1.639320  0.656015
2 -0.666795  1.639320  1.061254
3  0.747985  1.639320 -1.037145
4  0.136393       NaN -1.037145
5 -0.109069       NaN -1.037145

In [ ]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [ ]:
#Removing Duplicates
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1,1,2,3,3,4,4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [ ]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                             'Pastrami', 'corned beef', 'Bacon',
                            'pastrami', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
#Transforming Data Using a Function or Mapping
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [ ]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [ ]:
data['animal'] = lowercased.map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [ ]:
#replacing values
import pandas as pd
data = pd.Series([1., -999., 2., -999., 3.])
data

0      1.0
1   -999.0
2      2.0
3   -999.0
4      3.0
dtype: float64

In [ ]:
import numpy as np
data.replace(-999, np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

In [ ]:
#renaming axis indexes
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index = ['Ohio', 'Colorado', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [ ]:
data.rename(index=str.title, columns=str.upper)

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
data.rename(index={'OHIO':"INDIANA"},
           columns = {'three':'peekaboo'})

          one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
import pandas as pd
import numpy as np
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [ ]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [ ]:
pd.value_counts(cats)

/tmp/ipython-input-1485279302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [ ]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [ ]:
group_names = ['Youth', 'YoungAdult', 'MiddleAges', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAges', 'MiddleAges', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAges' < 'Senior']

In [ ]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.27, 0.51], (0.51, 0.75], (0.51, 0.75], (0.026, 0.27], (0.27, 0.51], ..., (0.75, 0.99], (0.026, 0.27], (0.51, 0.75], (0.27, 0.51], (0.75, 0.99]]
Length: 20
Categories (4, interval[float64, right]): [(0.026, 0.27] < (0.27, 0.51] < (0.51, 0.75] <
                                           (0.75, 0.99]]

In [ ]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(0.664, 2.748], (0.664, 2.748], (0.0576, 0.664], (-3.134, -0.699], (-3.134, -0.699], ..., (-0.699, 0.0576], (-0.699, 0.0576], (-3.134, -0.699], (0.0576, 0.664], (-0.699, 0.0576]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.134, -0.699] < (-0.699, 0.0576] < (0.0576, 0.664] <
                                           (0.664, 2.748]]

In [ ]:
pd.value_counts(cats)

/tmp/ipython-input-1485279302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)

(-3.134, -0.699]    250
(-0.699, 0.0576]    250
(0.0576, 0.664]     250
(0.664, 2.748]      250
Name: count, dtype: int64

In [ ]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(1.301, 2.748], (1.301, 2.748], (0.0576, 1.301], (-3.134, -1.309], (-1.309, 0.0576], ..., (-1.309, 0.0576], (-1.309, 0.0576], (-1.309, 0.0576], (0.0576, 1.301], (-1.309, 0.0576]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.134, -1.309] < (-1.309, 0.0576] < (0.0576, 1.301] <
                                           (1.301, 2.748]]

In [ ]:
#detecting and filtering outliers
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027538    -0.007389    -0.039045     0.034040
std       0.995178     0.981770     0.997596     0.988672
min      -3.088517    -2.754641    -2.884866    -3.685416
25%      -0.682211    -0.671722    -0.732852    -0.632515
50%      -0.037538     0.002275    -0.061236     0.035649
75%       0.674501     0.621486     0.622767     0.683835
max       4.087083     3.271861     3.470012     3.335824

In [ ]:
col = data[2]
col[np.abs(col) > 3]

857    3.033003
929    3.470012
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(axis=1)]

            0         1         2         3
140 -1.858560  3.271861  0.471501 -0.950403
170 -0.523468 -1.510870  0.675656  3.335824
338  4.087083 -0.304666  0.083395  1.171077
458 -0.364606  0.253928 -0.192596 -3.685416
529  3.100465  0.393477 -0.161519 -0.862492
857 -1.468865 -0.269268  3.033003 -0.531490
880 -3.071296  1.306933 -1.208201  0.540903
929 -0.614987 -1.132471  3.470012 -0.537390
945 -3.088517  0.022075 -0.967898  0.215297

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.028565    -0.007660    -0.039548     0.034390
std       0.990466     0.980898     0.995949     0.985257
min      -3.000000    -2.754641    -2.884866    -3.000000
25%      -0.682211    -0.671722    -0.732852    -0.632515
50%      -0.037538     0.002275    -0.061236     0.035649
75%       0.674501     0.621486     0.622767     0.683835
max       3.000000     3.000000     3.000000     3.000000

In [ ]:
np.sign(data).head()

     0    1    2    3
0  1.0 -1.0  1.0  1.0
1 -1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4  1.0 -1.0  1.0  1.0

In [ ]:
#permutation and random sampling
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)
sampler

array([4, 0, 1, 3, 2])

In [ ]:
print(df)

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
df.take(sampler)

    0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

In [ ]:
df.sample(n=3)

    0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

In [ ]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

3    6
4    4
3    6
2   -1
1    7
0    5
2   -1
1    7
2   -1
2   -1
dtype: int64

In [ ]:
#dummy variables
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1': range(6)})
pd.get_dummies(df['key'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [ ]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [ ]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [ ]:
#string manipulation
val = 'a,b,   guido'
val.split(',')

['a', 'b', '   guido']

In [ ]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [ ]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [ ]:
'::'.join(pieces)

'a::b::guido'

In [ ]:
'guido' in val

True

In [ ]:
val.index(',')

1

In [ ]:
val.find(':')

-1

In [ ]:
val.count(',')

2

In [ ]:
val.replace(',', '::')

'a::b::   guido'

In [ ]:
val.replace(',', '')

'ab   guido'

In [ ]:
#regular expression
import pandas as pd
import numpy as np
import re
text = "foo bar\t baz   \tqux"
re.split('\s+', text)

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-4236483142.py:5: SyntaxWarning: invalid escape sequence '\s'
  re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
regex = re.compile('\s+')
regex.split(text)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-1199159664.py:1: SyntaxWarning: invalid escape sequence '\s'
  regex = re.compile('\s+')

['foo', 'bar', 'baz', 'qux']

In [ ]:
regex.findall(text)

[' ', '\t ', '   \t']

In [ ]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [ ]:
m = regex.search(text)
m

In [ ]:
text[m.start():m.end()]

'dave@google.com'

In [ ]:
print(regex.match(text))

None

In [ ]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [ ]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
m = regex.match('wes@bright.net')
m.groups()

('wes', 'bright', 'net')

In [ ]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

In [ ]:
#Vectorized String Functions in pandas
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [ ]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [ ]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object